# Generated by Django 4.2.2 on 2023-06-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auction_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.URLField(blank=True, default='https://www.theseasonedhome.com/content/images/thumbs/default-image_450.png'),
        ),
    ]
