# Generated by Django 4.2.2 on 2023-06-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_item_poster_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
