# Generated by Django 4.2.2 on 2023-06-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_item_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='poster',
            field=models.CharField(max_length=64),
        ),
    ]
