# Generated by Django 4.2.2 on 2023-06-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_item_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
