# Generated by Django 4.2.2 on 2023-06-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_item_category_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/thumbnails/004/639/760/small/question-mark-with-shadow-circle-icon-isolated-on-white-background-vector.jpg'),
        ),
    ]
