# Generated by Django 4.2.2 on 2023-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='Items', to='auctions.item'),
        ),
    ]
