# Generated by Django 4.2.2 on 2023-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_watchlist_item_watchlist_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.item'),
        ),
    ]
