# Generated by Django 4.2.2 on 2023-06-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_item_closed_bidder_item_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bidder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bidder'),
        ),
    ]
