# Generated by Django 4.2.2 on 2023-06-15 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_bid_remove_item_bidder_delete_bidder_bid_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='created_at',
        ),
    ]
