# Generated by Django 4.2.2 on 2023-06-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='item',
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='auctions.item')),
                ('messages', models.ManyToManyField(blank=True, to='auctions.message')),
            ],
        ),
    ]
