# Generated by Django 4.2.2 on 2023-06-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_remove_message_item_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message_Groups',
        ),
    ]
