# Generated by Django 4.2.2 on 2023-06-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_rename_messages_message_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_Groups',
            new_name='Item_Message_Group',
        ),
    ]
